[tools]
rojo = "rojo-rbx/rojo@7.5.1"
lune = "lune-org/lune@0.9.4"
lute = "luau-lang/lute@0.1.0-nightly.20250701"
stylua = "JohnnyMorganz/StyLua@2.1.0"
wally = "UpliftGames/wally@0.3.2"
darklua = "SeaOfVoices/darklua@0.16.0"
